/** Illustrative outer envelopes in inches; none of these meshes are manufacturer CAD. */
export const CATALOG = [
  { type: 'sofa', name: 'Linen sofa', w: 86, d: 37, h: 32, color: '#d8ccba' },
  {
    type: 'sectional',
    name: 'L-shaped sectional',
    w: 120,
    d: 90,
    h: 34,
    seatDepth: 40,
    returnSide: 'left',
    color: '#d6c8b4',
  },
  {
    type: 'recliner',
    name: 'Recliner',
    w: 37,
    d: 38,
    h: 42,
    openDepth: 67,
    rearClearance: 12,
    open: false,
    color: '#9f7858',
  },
  {
    type: 'chair',
    name: 'Lounge chair',
    w: 30,
    d: 33,
    h: 31,
    color: '#a78e72',
  },
  {
    type: 'coffee',
    name: 'Coffee table',
    w: 44,
    d: 25,
    h: 16,
    color: '#6f4c32',
  },
  { type: 'rug', name: 'Area rug', w: 108, d: 84, h: 0.7, color: '#c9baa0' },
  {
    type: 'bed',
    name: 'Queen bed',
    w: 66,
    d: 86,
    h: 42,
    mattressW: 60,
    mattressD: 80,
    color: '#d6cbb9',
  },
  {
    type: 'bed',
    name: 'King bed',
    w: 80,
    d: 84,
    h: 34,
    mattressW: 76,
    mattressD: 80,
    color: '#d6cbb9',
  },
  {
    type: 'desk',
    name: '72 × 30 desk',
    w: 72,
    d: 30,
    h: 29,
    tvMonitorIn: 27,
    monitorLayout: 'triple',
    tvMonitorMode: 'work',
    color: '#aa8057',
  },
  {
    type: 'embody',
    name: 'Ergonomic rolling chair',
    w: 29.5,
    d: 29,
    h: 43.5,
    color: '#343d41',
  },
  {
    type: 'murphy',
    name: 'Queen bed + folding desk',
    w: 88,
    d: 16,
    h: 67,
    openDepth: 65,
    workDepth: 40,
    deskW: 83,
    deskD: 24,
    deskH: 29,
    open: false,
    officeMode: 'work',
    color: '#eeeae0',
  },
  {
    type: 'tv',
    name: 'Wall-mounted TV',
    w: 57,
    d: 2.2,
    h: 32,
    mountHeight: 60,
    extension: 12,
    swivel: 0,
    color: '#202729',
  },
  {
    type: 'dining',
    name: 'Dining table',
    w: 60,
    d: 34,
    h: 30,
    color: '#b18c66',
  },
  {
    type: 'stool',
    name: 'Counter stool',
    w: 18,
    d: 19,
    h: 37,
    color: '#a9845b',
  },
  {
    type: 'nightstand',
    name: 'Bedside table',
    w: 22,
    d: 18,
    h: 24,
    color: '#aa8057',
  },
  { type: 'plant', name: 'Floor plant', w: 24, d: 24, h: 60, color: '#547454' },
  {
    type: 'box',
    name: 'Custom furniture',
    w: 36,
    d: 24,
    h: 30,
    color: '#9a9287',
  },
];
export const FURNITURE_TYPES = [
  ...new Set(CATALOG.map((item) => item.type)),
  'console',
];
